/*행골라내기*/
/*직원의 이름, 성, 봉급 조회*/
/*단, 봉급이 10,000 이상인 직원 조회*/

SELECT FIRST_NAME , LAST_NAME , SALARY 
FROM EMPLOYEES e 
WHERE SALARY  >= 10000;

/* [실습] */
/* 직원의 이름, 성, 봉급을 조회한다.
 * 단, 이름이 David인 직원만 골라서 조회 */

SELECT FIRST_NAME 이름, 
   LAST_NAME 성, 
   SALARY "봉급"
FROM EMPLOYEES e 
WHERE FIRST_NAME = 'David';

/*별칭을 설정하여*/

SELECT FIRST_NAME 이름,  
   LAST_NAME 성, 		
   SALARY "봉급"
FROM EMPLOYEES e 		
--WHERE SALARY 봉급>=10000    
ORDER BY 봉급;

/* [NOT] */
SELECT FIRST_NAME 
FROM EMPLOYEES e 
WHERE NOT FIRST_NAME = 'David';





CREATE TABLE TBL_KINDERGARDEN(
	KINDER_NAME VARCHAR2(1000),
	KINDER_AGE NUMBER
);

/*DML*/
SELECT *FROM TBL_KINDERGARDEN tk;

/*INSERT*/
INSERT INTO  TBL_KINDERGARDEN (KINDER_NAME, KINDER_AGE)
VALUES('짱구',7);
INSERT INTO  TBL_KINDERGARDEN (KINDER_NAME, KINDER_AGE)
VALUES('수지',7);
INSERT INTO TBL_KINDERGARDEN 
VALUES(21, '철수'); -- 오류



/*UPDATE*/
UPDATE TBL_KINDERGARDEN
SET KINDER_NAME='훈이';

DELETE FROM TBL_KINDERGARDEN ts;


CREATE TABLE TBL_STUDENT (
   STUDENT_NUMBER NUMBER,
   STUDENT_NAME VARCHAR2(1000),
   STUDENT_MATH NUMBER,
   STUDENT_ENG NUMBER,
   STUDENT_KOR NUMBER,
   STUDENT_GRADE VARCHAR2(1000)
);

SELECT *FROM TBL_STUDENT ts;

/* [실습] */
/* 
 * 학생 테이블에 데이터를 추가한다.
 * 학생번호, 이름, 수학, 영어, 국어
 * 1, '김철수', 90, 90, 90
 * 2, '홍길동', 70, 25, 25
 * 3, '이유리', 89, 91, 77
 * 4. '김웅이', 48, 100, 92
 * 5. '신짱구', 22, 13, 9 
 * */

INSERT INTO TBL_STUDENT(STUDENT_NUMBER, STUDENT_NAME, STUDENT_MATH,STUDENT_ENG, STUDENT_KOR) 
VALUES(1, '김철수', 90,90,90);
INSERT INTO TBL_STUDENT(STUDENT_NUMBER, STUDENT_NAME, STUDENT_MATH,STUDENT_ENG, STUDENT_KOR) 
VALUES(2, '홍길동', 70, 25, 25);
INSERT INTO TBL_STUDENT(STUDENT_NUMBER, STUDENT_NAME, STUDENT_MATH,STUDENT_ENG, STUDENT_KOR) 
VALUES(3, '이유리', 89, 91, 77);
INSERT INTO TBL_STUDENT(STUDENT_NUMBER, STUDENT_NAME, STUDENT_MATH,STUDENT_ENG, STUDENT_KOR) 
VALUES(4, '김웅이', 48, 100, 92);
INSERT INTO TBL_STUDENT(STUDENT_NUMBER, STUDENT_NAME, STUDENT_MATH,STUDENT_ENG, STUDENT_KOR) 
VALUES(5, '신짱구', 22, 13, 9);

/* 전체 학생들의 이름과 평균 점수를 조회하기 (별칭도 넣기) */
SELECT STUDENT_NAME, ROUND((STUDENT_MATH+STUDENT_ENG+STUDENT_KOR) /3) "평균점수"
FROM TBL_STUDENT ts;
/* 
 * 학생의 평균 점수를 구하고 학점을 수정하기 
 * 
 * A : 90점 이상
 * B : 80점 이상 90점 미만
 * C : 50점 이상 80점 미만
 * F : 50점 미만 
 * */
UPDATE TBL_STUDENT 
SET STUDENT_GRADE='A'
WHERE (STUDENT_MATH+STUDENT_ENG+STUDENT_KOR) /3 >=90;

UPDATE TBL_STUDENT 
SET STUDENT_GRADE='B'
WHERE (STUDENT_MATH+STUDENT_ENG+STUDENT_KOR) /3 >=80
	AND (STUDENT_MATH+STUDENT_ENG+STUDENT_KOR) /3 <90;

UPDATE TBL_STUDENT 
SET STUDENT_GRADE='C'
WHERE (STUDENT_MATH+STUDENT_ENG+STUDENT_KOR) /3 >=50
	AND (STUDENT_MATH+STUDENT_ENG+STUDENT_KOR) /3 <80;

UPDATE TBL_STUDENT 
SET STUDENT_GRADE='F'
WHERE (STUDENT_MATH+STUDENT_ENG+STUDENT_KOR) /3 <50;

SELECT *FROM TBL_STUDENT 


/*학생의 수학, 영어, 국어 점수 중 한 과목이라도 50점 미만이 아니고
 * 학점이 B 이상인 학생만 학생 번호, 이름, 학점 조회(별칭도 넣기)
 */

SELECT STUDENT_NUMBER "학생 번호", 
   STUDENT_NAME 이름, 
   STUDENT_GRADE 학점
FROM TBL_STUDENT ts 
WHERE NOT (STUDENT_MATH < 50 OR 
   STUDENT_ENG < 50 OR
   STUDENT_KOR < 50)
AND STUDENT_GRADE IN('A', 'B');


CREATE TABLE TBL_USER(
	USER_NAME VARCHAR2(1000),
	USER_AGE NUMBER
);

SELECT *FROM TBL_USER ;
ALTER TABLE TBL_USER RENAME TO TBL_MY_USER;
SELECT *FROM TBL_MY_USER ;

/*컬럼 추가*/
ALTER TABLE TBL_MY_USER  ADD(USER_GENDER CHAR(4));

/*컬럼명 수정*/
ALTER TABLE TBL_MY_USER RENAME COLUMN  USER_NAME TO USER_NICKNAME;

/*컬럼 삭제*/
ALTER TABLE TBL_MY_USER  DROP COLUMN USER_GENDER;

/*컬럼 타입(자료형) 수정*/
ALTER TABLE TBL_MY_USER MODIFY(USER_NICKNAME VARCHAR2(500));