/* [실습] */
/* 
 * 요구사항
 * 
 * 유치원을 하려고 하는데, 아이들이 체험학습 프로그램을 신청해야 합니다.
 * 아이들 정보는 이름, 나이, 성별이 필요하고 
 * 학부모는 이름, 나이, 주소, 전화번호, 성별이 필요해요.
 * 체험학습은 체험학습 제목, 체험학습 내용, 이벤트 이미지 여러 장이 필요합니다.
 * 아이들은 여러 번 체험학습에 등록할 수 있어요. 
 * */

/* 아이들 정보 */
CREATE TABLE TBL_PARENT(
   ID NUMBER CONSTRAINT PK_PARENT PRIMARY KEY,
   PARENT_NAME VARCHAR2(1000) NOT NULL,
   PARENT_AGE NUMBER NOT NULL,
   PARENT_ADDRESS VARCHAR2(1000) NOT NULL,
   PARENT_PHONE_NUMBER VARCHAR2(1000) NOT NULL UNIQUE,
   PARENT_GENDER VARCHAR2(1000) NOT NULL
);

/* 학부모 정보 */
CREATE TABLE TBL_CHILD(
   ID NUMBER CONSTRAINT PK_CHILD PRIMARY KEY,
   CHILD_NAME VARCHAR2 (1000) NOT NULL,
   CHILD_AGE NUMBER NOT NULL,
   CHILD_GENDER VARCHAR2 (1000) NOT NULL,
   PARENT_ID NUMBER ,
   CONSTRAINT FK_CHILD_PARENT FOREIGN KEY (PARENT_ID)
   REFERENCES TBL_PARENT (ID)
);

/* 체험학습 정보 */
CREATE TABLE TBL_FIELD_TRIP(
   ID NUMBER CONSTRAINT PK_FIELD_TRIP PRIMARY KEY,
   FIELD_TRIP_TITLE VARCHAR2 (1000) NOT NULL,
   FIELD_TRIP_CONTENT VARCHAR2 (1000)
);

/* 체험학습에 대한 이벤트 이미지 */
CREATE TABLE TBL_FIELD_TRIP_FILE(
   ID NUMBER CONSTRAINT PK_FIELD_TRIP_FILE PRIMARY KEY,
   FILE_ORIGINAL_NAME VARCHAR2 (1000) NOT NULL,   -- 이미지 업로드 시 기존 파일명
   FILE_SYSTEM_NAME VARCHAR2 (1000) NOT NULL,      -- 이미지 업로드 시 서버에 저장될 파일명   
   FILE_UPLOAD_DATE DATE,
   FIELD_TRIP_ID NUMBER,
   CONSTRAINT FK_FIELD_TRIP_FILE_FIELD_TRIP FOREIGN KEY (FIELD_TRIP_ID)
   REFERENCES TBL_FIELD_TRIP (ID)
);

/* 체험학습 신청 정보 */
CREATE TABLE TBL_APPLY(
   ID NUMBER CONSTRAINT PK_APPLY PRIMARY KEY,
   CHILD_ID NUMBER,
   FIELD_TRIP_ID NUMBER ,
   CONSTRAINT FK_APPLY_CHILD FOREIGN KEY(CHILD_ID)
   REFERENCES TBL_CHILD (ID),
   CONSTRAINT FK_APPLY_FIELD_TRIP FOREIGN KEY(FIELD_TRIP_ID)
   REFERENCES TBL_FIELD_TRIP (ID)
);






SELECT *FROM PLAYER p ;
/* [실습] */
/* PLAYER 테이블에서 WEIGHT가 70 이상이고, 80 이하인 선수 검색 */
SELECT * FROM PLAYER p 
WHERE WEIGHT >= 70 AND WEIGHT <= 80
ORDER BY WEIGHT ;

SELECT * FROM PLAYER p 
WHERE WEIGHT BETWEEN 70 AND 80
ORDER BY WEIGHT ;

/* PLAYER 테이블에서 TEAM_ID가 'K03'이고, HEIGHT가 180 미만인 선수 검색 */
SELECT * FROM PLAYER p 
WHERE TEAM_ID = 'K03' AND HEIGHT < 180;

/* PLAYER 테이블에서 TEAM_ID가 'K06'이고, NICKNAME이 '제리'인 선수 검색 (*제리 : 한글) */
SELECT * FROM PLAYER p 
WHERE TEAM_ID = 'K06' AND NICKNAME = '제리';

/* PLAYER 테이블에서 HEIGHT가 170 이상이고, WEIGHT가 80 이상인 선수 이름 검색 */
SELECT PLAYER_NAME 
FROM PLAYER p 
WHERE HEIGHT >= 170 AND WEIGHT >= 80;

/* STADIUM 테이블에서 SEAT_COUNT가 30000초과이고, 41000이하인 경기장 검색 */
SELECT * FROM STADIUM s 
WHERE SEAT_COUNT > 30000 AND SEAT_COUNT <= 41000;

/* PLAYER 테이블에서 TEAM_ID가 'K02'이거나 'K07'이고, 포지션은 'MF'인 선수 검색 */
/* AND가 OR보다 우선순위가 높다. */
SELECT * FROM PLAYER p 
WHERE (TEAM_ID = 'K02' OR TEAM_ID = 'K07') AND "POSITION" = 'MF';

/* IN()을 사용해도 된다. */
SELECT * FROM PLAYER p 
WHERE TEAM_ID IN('K02', 'K07') AND "POSITION" = 'MF';


